import 'tattoo_template.dart';

/// Beispiel-Katalog. In einer echten App würde diese Liste aus einem
/// Backend/einer Datenbank geladen werden.
final List<TattooTemplate> mockCatalog = [
  const TattooTemplate(
    id: 't001',
    templateNumber: 'SPT-001',
    name: 'Drachen-Tribal',
    category: TemplateCategory.tribal,
    price: 14.90,
    description: 'Geschwungenes Tribal-Motiv in Drachenform, ideal für Oberarm oder Rücken.',
  ),
  const TattooTemplate(
    id: 't002',
    templateNumber: 'SPT-002',
    name: 'Wolf im Mondlicht',
    category: TemplateCategory.tier,
    price: 18.50,
    description: 'Detailreicher Wolfskopf vor Vollmond-Silhouette.',
  ),
  const TattooTemplate(
    id: 't003',
    templateNumber: 'SPT-003',
    name: 'Kirschblütenzweig',
    category: TemplateCategory.blumen,
    price: 12.00,
    description: 'Zarter Zweig mit Kirschblüten, gut für Handgelenk oder Schulter.',
  ),
  const TattooTemplate(
    id: 't004',
    templateNumber: 'SPT-004',
    name: '"Stay Wild" Schriftzug',
    category: TemplateCategory.schriftzug,
    price: 9.90,
    description: 'Verschnörkelter Schriftzug in Script-Optik.',
  ),
  const TattooTemplate(
    id: 't005',
    templateNumber: 'SPT-005',
    name: 'Kompass-Symbol',
    category: TemplateCategory.symbol,
    price: 15.00,
    description: 'Klassischer Kompass mit feinen Linienverzierungen.',
  ),
  const TattooTemplate(
    id: 't006',
    templateNumber: 'SPT-006',
    name: 'Phönix in Flammen',
    category: TemplateCategory.fantasie,
    price: 22.00,
    description: 'Großflächiges Phönix-Motiv, wirkt am besten auf Rücken oder Brust.',
  ),
  const TattooTemplate(
    id: 't007',
    templateNumber: 'SPT-007',
    name: 'Maori-Band',
    category: TemplateCategory.tribal,
    price: 13.50,
    description: 'Durchgehendes Maori-Bandmuster für Oberarm oder Wade.',
  ),
  const TattooTemplate(
    id: 't008',
    templateNumber: 'SPT-008',
    name: 'Schwalben-Paar',
    category: TemplateCategory.tier,
    price: 11.00,
    description: 'Zwei fliegende Schwalben, klassisches Motiv für das Schlüsselbein.',
  ),
  const TattooTemplate(
    id: 't009',
    templateNumber: 'SPT-009',
    name: 'Rosenranke',
    category: TemplateCategory.blumen,
    price: 16.90,
    description: 'Rosenranke mit Dornen, gut kombinierbar mit Schriftzügen.',
  ),
  const TattooTemplate(
    id: 't010',
    templateNumber: 'SPT-010',
    name: '"Free Soul" Schriftzug',
    category: TemplateCategory.schriftzug,
    price: 9.90,
    description: 'Moderner Schriftzug in serifenloser Handschrift.',
  ),
  const TattooTemplate(
    id: 't011',
    templateNumber: 'SPT-011',
    name: 'Mondphasen',
    category: TemplateCategory.symbol,
    price: 13.00,
    description: 'Reihe von Mondphasen, gut für Unterarm oder Rippen.',
  ),
  const TattooTemplate(
    id: 't012',
    templateNumber: 'SPT-012',
    name: 'Drache & Tiger',
    category: TemplateCategory.fantasie,
    price: 24.50,
    description: 'Großes, detailreiches Motiv im asiatischen Stil.',
  ),
  const TattooTemplate(
    id: 't013',
    templateNumber: 'SPT-013',
    name: 'Löwenkopf',
    category: TemplateCategory.tier,
    price: 19.90,
    description: 'Kraftvoller Löwenkopf mit ausladender Mähne.',
  ),
  const TattooTemplate(
    id: 't014',
    templateNumber: 'SPT-014',
    name: 'Sonnenblume',
    category: TemplateCategory.blumen,
    price: 12.50,
    description: 'Realistische Sonnenblume mit feinen Blattadern.',
  ),
  const TattooTemplate(
    id: 't015',
    templateNumber: 'SPT-015',
    name: 'Geometrisches Mandala',
    category: TemplateCategory.symbol,
    price: 17.00,
    description: 'Symmetrisches Mandala-Muster, gut für Schulterblatt.',
  ),
  const TattooTemplate(
    id: 't016',
    templateNumber: 'SPT-016',
    name: 'Fee im Mondlicht',
    category: TemplateCategory.fantasie,
    price: 20.00,
    description: 'Filigrane Fee-Illustration mit Federflügeln.',
  ),

  // --- Winterberg-Erweiterung (SPT-017 .. SPT-046) ---
  const TattooTemplate(
    id: 't017',
    templateNumber: 'SPT-017',
    name: 'W-Monogramm Wintersport',
    category: TemplateCategory.schriftzug,
    price: 11.90,
    description:
        'Eigens gestaltetes, schlichtes W-Monogramm mit gekreuzten Ski im Hintergrund – '
        'kein Abbild eines echten Stadt- oder Vereinslogos, sondern ein eigenständiges '
        'Wintersport-Design.',
  ),
  const TattooTemplate(
    id: 't018',
    templateNumber: 'SPT-018',
    name: 'Carving Ski',
    category: TemplateCategory.ski,
    price: 15.90,
    description: 'Zwei gekreuzte Skier mit Stöcken, klassisches Motiv für Wintersportfans.',
  ),
  const TattooTemplate(
    id: 't019',
    templateNumber: 'SPT-019',
    name: 'Schwarze Piste',
    category: TemplateCategory.ski,
    price: 17.50,
    description: 'Abfahrtsläufer in dynamischer Haltung, minimalistisch gehalten.',
  ),
  const TattooTemplate(
    id: 't020',
    templateNumber: 'SPT-020',
    name: 'Schneeflocke Alpin',
    category: TemplateCategory.ski,
    price: 9.90,
    description: 'Stilisierte Schneeflocke, gut kombinierbar mit anderen Wintersport-Motiven.',
  ),
  const TattooTemplate(
    id: 't021',
    templateNumber: 'SPT-021',
    name: 'Downhill Trail',
    category: TemplateCategory.bike,
    price: 16.90,
    description: 'Mountainbike in Seitenansicht mit angedeuteter Reifenspur.',
  ),
  const TattooTemplate(
    id: 't022',
    templateNumber: 'SPT-022',
    name: 'Kettenrad',
    category: TemplateCategory.bike,
    price: 12.50,
    description: 'Fahrrad-Kettenrad als grafisches Rund-Symbol.',
  ),
  const TattooTemplate(
    id: 't023',
    templateNumber: 'SPT-023',
    name: 'Trail Lenker',
    category: TemplateCategory.bike,
    price: 14.90,
    description: 'Bike-Lenker mit angedeuteten Trail-Linien im Hintergrund.',
  ),
  const TattooTemplate(
    id: 't024',
    templateNumber: 'SPT-024',
    name: 'Eiskanal Sprint',
    category: TemplateCategory.bob,
    price: 19.90,
    description: 'Zweier-Bob in voller Fahrt – Motiv für Bobbahn-Fans.',
  ),
  const TattooTemplate(
    id: 't025',
    templateNumber: 'SPT-025',
    name: 'Startnummer Eins',
    category: TemplateCategory.bob,
    price: 10.90,
    description: 'Grafische Startnummer mit Eiskristall-Rahmen.',
  ),
  const TattooTemplate(
    id: 't026',
    templateNumber: 'SPT-026',
    name: 'Bierkrug Prost',
    category: TemplateCategory.getraenke,
    price: 13.90,
    description: 'Klassischer Bierkrug mit Schaumkrone, für alle Après-Ski-Fans.',
  ),
  const TattooTemplate(
    id: 't027',
    templateNumber: 'SPT-027',
    name: 'Cheers Schriftzug',
    category: TemplateCategory.getraenke,
    price: 11.50,
    description: '"Cheers"-Schriftzug mit zwei angestoßenen Gläsern.',
  ),
  const TattooTemplate(
    id: 't028',
    templateNumber: 'SPT-028',
    name: 'Hopfen & Malz',
    category: TemplateCategory.getraenke,
    price: 15.90,
    description: 'Hopfenzweig, der sich um ein Bierglas rankt.',
  ),
  const TattooTemplate(
    id: 't029',
    templateNumber: 'SPT-029',
    name: 'Après-Ski Shot',
    category: TemplateCategory.getraenke,
    price: 9.50,
    description: 'Schnapsglas mit feinem Schneeflocken-Muster, Après-Ski-Stimmung.',
  ),
  const TattooTemplate(
    id: 't030',
    templateNumber: 'SPT-030',
    name: 'Alpenadler',
    category: TemplateCategory.tier,
    price: 18.90,
    description: 'Adler mit ausgebreiteten Schwingen über einer Berggipfel-Silhouette.',
  ),
  const TattooTemplate(
    id: 't031',
    templateNumber: 'SPT-031',
    name: 'Steinbock',
    category: TemplateCategory.tier,
    price: 17.90,
    description: 'Alpensteinbock im Profil mit markanten geschwungenen Hörnern.',
  ),
  const TattooTemplate(
    id: 't032',
    templateNumber: 'SPT-032',
    name: 'Wolfsrudel',
    category: TemplateCategory.tier,
    price: 19.50,
    description: 'Zwei Wolfsköpfe Rücken an Rücken, symmetrisch angeordnet.',
  ),
  const TattooTemplate(
    id: 't033',
    templateNumber: 'SPT-033',
    name: 'Kompassrose',
    category: TemplateCategory.symbol,
    price: 14.50,
    description: 'Klassische Kompassrose mit feinen Linienverzierungen.',
  ),
  const TattooTemplate(
    id: 't034',
    templateNumber: 'SPT-034',
    name: 'Anker Nautik',
    category: TemplateCategory.symbol,
    price: 13.50,
    description: 'Klassisches Anker-Motiv, mit Seil umwickelt.',
  ),
  const TattooTemplate(
    id: 't035',
    templateNumber: 'SPT-035',
    name: 'Mandala Rund',
    category: TemplateCategory.symbol,
    price: 16.50,
    description: 'Filigranes, rundes Mandala-Muster.',
  ),
  const TattooTemplate(
    id: 't036',
    templateNumber: 'SPT-036',
    name: 'Blitz & Wolke',
    category: TemplateCategory.symbol,
    price: 10.90,
    description: 'Stilisierter Blitz mit angedeuteter Gewitterwolke.',
  ),
  const TattooTemplate(
    id: 't037',
    templateNumber: 'SPT-037',
    name: 'Bergpanorama',
    category: TemplateCategory.symbol,
    price: 15.50,
    description: 'Dreifache Bergsilhouette mit aufgehender Sonne.',
  ),
  const TattooTemplate(
    id: 't038',
    templateNumber: 'SPT-038',
    name: 'Edelweiß',
    category: TemplateCategory.blumen,
    price: 12.90,
    description: 'Klassisches Alpen-Edelweiß, filigran gezeichnet.',
  ),
  const TattooTemplate(
    id: 't039',
    templateNumber: 'SPT-039',
    name: 'Rosenranke Fein',
    category: TemplateCategory.blumen,
    price: 16.90,
    description: 'Verschlungene Rosenranke mit Dornen.',
  ),
  const TattooTemplate(
    id: 't040',
    templateNumber: 'SPT-040',
    name: 'Kirschblüte Fein',
    category: TemplateCategory.blumen,
    price: 12.00,
    description: 'Zarter Kirschblütenzweig, Ergänzung zu SPT-003.',
  ),
  const TattooTemplate(
    id: 't041',
    templateNumber: 'SPT-041',
    name: 'Drachenauge',
    category: TemplateCategory.fantasie,
    price: 18.50,
    description: 'Stilisiertes Drachenauge, umrahmt von Flammen.',
  ),
  const TattooTemplate(
    id: 't042',
    templateNumber: 'SPT-042',
    name: 'Phönix Aufstieg',
    category: TemplateCategory.fantasie,
    price: 21.90,
    description: 'Phönix im Aufflug mit weit gespannten Flügeln.',
  ),
  const TattooTemplate(
    id: 't043',
    templateNumber: 'SPT-043',
    name: 'Traumfänger',
    category: TemplateCategory.fantasie,
    price: 17.50,
    description: 'Klassischer Traumfänger mit herabhängenden Federn.',
  ),
  const TattooTemplate(
    id: 't044',
    templateNumber: 'SPT-044',
    name: 'Tribal Welle',
    category: TemplateCategory.tribal,
    price: 14.90,
    description: 'Fließendes, symmetrisches Wellen-Tribal.',
  ),
  const TattooTemplate(
    id: 't045',
    templateNumber: 'SPT-045',
    name: 'Tribal Flamme',
    category: TemplateCategory.tribal,
    price: 15.90,
    description: 'Tribal-Muster in geschwungener Flammenform.',
  ),
  const TattooTemplate(
    id: 't046',
    templateNumber: 'SPT-046',
    name: '"Für immer" Schriftzug',
    category: TemplateCategory.schriftzug,
    price: 9.90,
    description: 'Geschwungener Schriftzug, klassisches Freundschafts-/Partner-Motiv.',
  ),
];
