import 'tattoo_template.dart';

/// Beispiel-Katalog. In einer echten App würde diese Liste aus einem
/// Backend/einer Datenbank geladen werden.
final List<TattooTemplate> mockCatalog = [
  const TattooTemplate(
    id: 't001',
    templateNumber: 'SPT-001',
    name: 'Drachen-Tribal',
    category: TemplateCategory.tribal,
    price: 14.90,
    description: 'Geschwungenes Tribal-Motiv in Drachenform, ideal für Oberarm oder Rücken.',
  ),
  const TattooTemplate(
    id: 't002',
    templateNumber: 'SPT-002',
    name: 'Wolf im Mondlicht',
    category: TemplateCategory.tier,
    price: 18.50,
    description: 'Detailreicher Wolfskopf vor Vollmond-Silhouette.',
  ),
  const TattooTemplate(
    id: 't003',
    templateNumber: 'SPT-003',
    name: 'Kirschblütenzweig',
    category: TemplateCategory.blumen,
    price: 12.00,
    description: 'Zarter Zweig mit Kirschblüten, gut für Handgelenk oder Schulter.',
  ),
  const TattooTemplate(
    id: 't004',
    templateNumber: 'SPT-004',
    name: '"Stay Wild" Schriftzug',
    category: TemplateCategory.schriftzug,
    price: 9.90,
    description: 'Verschnörkelter Schriftzug in Script-Optik.',
  ),
  const TattooTemplate(
    id: 't005',
    templateNumber: 'SPT-005',
    name: 'Kompass-Symbol',
    category: TemplateCategory.symbol,
    price: 15.00,
    description: 'Klassischer Kompass mit feinen Linienverzierungen.',
  ),
  const TattooTemplate(
    id: 't006',
    templateNumber: 'SPT-006',
    name: 'Phönix in Flammen',
    category: TemplateCategory.fantasie,
    price: 22.00,
    description: 'Großflächiges Phönix-Motiv, wirkt am besten auf Rücken oder Brust.',
  ),
  const TattooTemplate(
    id: 't007',
    templateNumber: 'SPT-007',
    name: 'Maori-Band',
    category: TemplateCategory.tribal,
    price: 13.50,
    description: 'Durchgehendes Maori-Bandmuster für Oberarm oder Wade.',
  ),
  const TattooTemplate(
    id: 't008',
    templateNumber: 'SPT-008',
    name: 'Schwalben-Paar',
    category: TemplateCategory.tier,
    price: 11.00,
    description: 'Zwei fliegende Schwalben, klassisches Motiv für das Schlüsselbein.',
  ),
  const TattooTemplate(
    id: 't009',
    templateNumber: 'SPT-009',
    name: 'Rosenranke',
    category: TemplateCategory.blumen,
    price: 16.90,
    description: 'Rosenranke mit Dornen, gut kombinierbar mit Schriftzügen.',
  ),
  const TattooTemplate(
    id: 't010',
    templateNumber: 'SPT-010',
    name: '"Free Soul" Schriftzug',
    category: TemplateCategory.schriftzug,
    price: 9.90,
    description: 'Moderner Schriftzug in serifenloser Handschrift.',
  ),
  const TattooTemplate(
    id: 't011',
    templateNumber: 'SPT-011',
    name: 'Mondphasen',
    category: TemplateCategory.symbol,
    price: 13.00,
    description: 'Reihe von Mondphasen, gut für Unterarm oder Rippen.',
  ),
  const TattooTemplate(
    id: 't012',
    templateNumber: 'SPT-012',
    name: 'Drache & Tiger',
    category: TemplateCategory.fantasie,
    price: 24.50,
    description: 'Großes, detailreiches Motiv im asiatischen Stil.',
  ),
  const TattooTemplate(
    id: 't013',
    templateNumber: 'SPT-013',
    name: 'Löwenkopf',
    category: TemplateCategory.tier,
    price: 19.90,
    description: 'Kraftvoller Löwenkopf mit ausladender Mähne.',
  ),
  const TattooTemplate(
    id: 't014',
    templateNumber: 'SPT-014',
    name: 'Sonnenblume',
    category: TemplateCategory.blumen,
    price: 12.50,
    description: 'Realistische Sonnenblume mit feinen Blattadern.',
  ),
  const TattooTemplate(
    id: 't015',
    templateNumber: 'SPT-015',
    name: 'Geometrisches Mandala',
    category: TemplateCategory.symbol,
    price: 17.00,
    description: 'Symmetrisches Mandala-Muster, gut für Schulterblatt.',
  ),
  const TattooTemplate(
    id: 't016',
    templateNumber: 'SPT-016',
    name: 'Fee im Mondlicht',
    category: TemplateCategory.fantasie,
    price: 20.00,
    description: 'Filigrane Fee-Illustration mit Federflügeln.',
  ),
];
